import {
  Model,
  DataTypes,
  Optional,
} from "sequelize";
import sequelize from "../sequelize";
import { Call } from "./call.model";
import { UserModel } from "./user.model";

// ----------
// 1️⃣ Define attributes
// ----------
export interface CallFeedbackAttributes {
  id: string;
  call_id: string;
  kind: "GUEST" | "USER";
  ref_id: string;
  score: number;
  feedback: string | null;
  created_at: Date;
  updated_at: Date;
}

// ----------
// 2️⃣ Define creation attributes (omit fields auto-generated by DB)
// ----------
export type CallFeedbackCreationAttributes = Optional<
  CallFeedbackAttributes,
  "id" | "created_at" | "updated_at"
>;

// ----------
// 3️⃣ Define the typed Model
// ----------
export class CallFeedback
  extends Model<CallFeedbackAttributes, CallFeedbackCreationAttributes>
  implements CallFeedbackAttributes
{
  public id!: string;
  public call_id!: string;
  public kind!: "GUEST" | "USER";
  public ref_id!: string;
  public score!: number;
  public feedback!: string | null;
  public created_at!: Date;
  public updated_at!: Date;

  // Associations
  public call?: Call;
  public user?: UserModel;
}

// ----------
// 4️⃣ Initialize the model
// ----------
CallFeedback.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
      allowNull: false,
    },
    call_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "calls",
        key: "id",
      },
      onDelete: "CASCADE",
    },
    kind: {
      type: DataTypes.ENUM("GUEST", "USER"),
      allowNull: false,
    },
    ref_id: {
      type: DataTypes.UUID,
      allowNull: false,
      comment: "ID dari guest / user / extension yang memberikan feedback",
    },
    score: {
      type: DataTypes.SMALLINT,
      allowNull: false,
      validate: {
        min: 1,
        max: 5,
      },
      comment: "Score 1-5",
    },
    feedback: {
      type: DataTypes.STRING(500),
      allowNull: true,
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    updated_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    sequelize,
    modelName: "CallFeedback",
    tableName: "call_feedbacks",
    timestamps: true,
    createdAt: "created_at",
    updatedAt: "updated_at",
  }
);

