import {
  Model,
  DataTypes,
  Optional,
} from "sequelize";
import sequelize from "../sequelize";
import { Organization } from "./organization.model";
import { UserModel } from "./user.model";

// ----------
// 1️⃣ Define attributes
// ----------
export interface OrganizationChangeLogAttributes {
  id: number;
  organization_id: string;
  old_data_json: string | null;
  new_data_json: string;
  user_id: string;
  created_at: Date;
}

// ----------
// 2️⃣ Define creation attributes (omit fields auto-generated by DB)
// ----------
export type OrganizationChangeLogCreationAttributes = Optional<
  OrganizationChangeLogAttributes,
  "id" | "created_at"
>;

// ----------
// 3️⃣ Define the typed Model
// ----------
export class OrganizationChangeLog
  extends Model<OrganizationChangeLogAttributes, OrganizationChangeLogCreationAttributes>
  implements OrganizationChangeLogAttributes
{
  public id!: number;
  public organization_id!: string;
  public old_data_json!: string | null;
  public new_data_json!: string;
  public user_id!: string;
  public created_at!: Date;

  // Associations
  public organization?: Organization;
  public user?: UserModel;
}

// ----------
// 4️⃣ Initialize the model
// ----------
OrganizationChangeLog.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    organization_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "organizations",
        key: "id",
      },
      onDelete: "CASCADE",
    },
    old_data_json: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    new_data_json: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    user_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "users",
        key: "id",
      },
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    sequelize,
    modelName: "OrganizationChangeLog",
    tableName: "organization_change_logs",
    timestamps: false,
  }
);

