import {
  Model,
  DataTypes,
  Optional,
  Sequelize,
} from "sequelize";
import sequelize from "../sequelize";
import { OrganizationUser } from "./organizationUser.model";
// import "./associations";

// ----------
// 1️⃣ Define attributes
// ----------
export interface OrganizationAttributes {
  id: string;
  name: string;
  total_member: number;
  description?: string | null;
  address?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  organization_status_id: number;
  primary_contact_full_name?: string | null;
  primary_contact_phone_number?: string | null;
  reviewer_notes?: string | null;
  internal_notes?: string | null;
  primary_did_number?: string | null;
  created_by: string;
  updated_by: string;
  created_at: Date;
  updated_at: Date;
}

// ----------
// 2️⃣ Define creation attributes (omit fields auto-generated by DB)
// ----------
export type OrganizationCreationAttributes = Optional<
  OrganizationAttributes,
  | "id"
  | "created_at"
  | "updated_at"
  | "internal_notes"
>;

// ----------
// 3️⃣ Define the typed Model
// ----------
export class Organization
  extends Model<OrganizationAttributes, OrganizationCreationAttributes>
  implements OrganizationAttributes
{
  public id!: string;
  public name!: string;
  public total_member!: number;
  public description!: string | null;
  public address!: string | null;
  public latitude!: number | null;
  public longitude!: number | null;
  public organization_status_id!: number;
  public primary_contact_full_name!: string | null;
  public primary_contact_phone_number!: string | null;
  public reviewer_notes!: string | null;
  public internal_notes!: string | null;
  public primary_did_number!: string | null;
  public created_by!: string;
  public updated_by!: string;
  public created_at!: Date;
  public updated_at!: Date;
}

// ----------
// 4️⃣ Initialize the model
// ----------
Organization.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    total_member: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 1,
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    address: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    latitude: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
    longitude: {
      type: DataTypes.INTEGER,
      allowNull: true,
    },
    organization_status_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    primary_contact_full_name: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    primary_contact_phone_number: {
      type: DataTypes.STRING,
      allowNull: true,
    },
    reviewer_notes: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    internal_notes: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    primary_did_number: {
      type: DataTypes.STRING(50),
      allowNull: true,
    },
    created_by: {
      type: DataTypes.UUID,
      allowNull: false,
    },
    updated_by: {
      type: DataTypes.UUID,
      allowNull: false,
    },
    created_at: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
    updated_at: {
      type: DataTypes.DATE,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    sequelize,
    modelName: "Organization",
    tableName: "organizations",
    timestamps: false, // disable Sequelize automatic timestamps since we have our own
  }
);

// In organization.model.ts (after Organization.init)
Organization.hasMany(OrganizationUser, { foreignKey: "organization_id", as: "organizationUsers" });

OrganizationUser.belongsTo(Organization, { foreignKey: "organization_id" });