import {
  Model,
  DataTypes,
  Optional,
} from "sequelize";
import sequelize from "../sequelize";
import { Extension } from "./extension.model";
import { UserModel } from "./user.model";

// ----------
// 1️⃣ Define attributes
// ----------
export interface OrganizationUserLogAttributes {
  id: number;
  extension_id: string | null;
  user_id: string;
  old_data_json: string;
  new_data_json: string;
  created_by: string;
  created_at: Date;
}

// ----------
// 2️⃣ Define creation attributes (omit fields auto-generated by DB)
// ----------
export type OrganizationUserLogCreationAttributes = Optional<
  OrganizationUserLogAttributes,
  "id" | "created_at"
>;

// ----------
// 3️⃣ Define the typed Model
// ----------
export class OrganizationUserLog
  extends Model<OrganizationUserLogAttributes, OrganizationUserLogCreationAttributes>
  implements OrganizationUserLogAttributes
{
  public id!: number;
  public extension_id!: string | null;
  public user_id!: string;
  public old_data_json!: string;
  public new_data_json!: string;
  public created_by!: string;
  public created_at!: Date;

  // Associations
  public extension?: Extension;
  public user?: UserModel;
  public createdByUser?: UserModel;
}

// ----------
// 4️⃣ Initialize the model
// ----------
OrganizationUserLog.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    extension_id: {
      type: DataTypes.UUID,
      allowNull: true,
      references: {
        model: "extensions",
        key: "id",
      },
      onDelete: "SET NULL",
    },
    user_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "users",
        key: "id",
      },
    },
    old_data_json: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    new_data_json: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    created_by: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: "users",
        key: "id",
      },
    },
    created_at: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
  },
  {
    sequelize,
    modelName: "OrganizationUserLog",
    tableName: "organization_user_logs",
    timestamps: false,
  }
);

